### ISSUE TITLE
AttrDict instance has no attribute rewards

### ISSUE THREAD

**Issue by szhang42** [Alab-NII/PhraseRL#1]
Hello,

Thanks for the great paper and code! While I am implementing the code to do the reinforcement learning using the " python bin/policy.py -c configs/disc.toml -s 0 -o outputs/disc-rl -m outputs/disc/best_model.pt ". It occurs the error like the below. Could you please advise what I should change and the potential reasons for this error? Thanks!

Traceback (most recent call last):
  File "bin/policy.py", line 19, in <module>
    policy.run(opt)
  File "/PhraseRL/bin/phraserl/scripts/policy.py", line 62, in run
    policy(opt, agent, train_task)
  File "/PhraseRL/bin/phraserl/scripts/policy.py", line 13, in policy
    get_task_metrics(opt.rewards), coefs=opt.get("coefs", None)
  File "/.local/lib/python3.8/site-packages/attrdict/mixins.py", line 80, in __getattr__
    raise AttributeError(
AttributeError: 'AttrDict' instance has no attribute 'rewards'

**Comment by takatoy** [comment]
@szhang42 
Sorry for the late response.
Thank you for your interest in our paper and codes!

The error is due to my mistake, which I forgot to upload the configuration file for RL.
I've added the config, updated the README, and confirmed that it trains on my environment.

Specifically, try running the RL with the below code.
```sh
python bin/policy.py -c outputs/disc/config.toml configs/rl.toml -s 0 -o outputs/disc-rl -m outputs/disc/best_model.pt
```

Thank you!
